language: python
python:
  - "3.6.7"

env:
  - TEST_DATABASE="postgres://admin:admin123@localhost:5432/politico_test"
  
# install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE politico_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres

# run pytest
script:
  - pytest --cov=app tests

# then post the results to coveralls
after_success:
  - coveralls
