language: python
python:
  - "3.6.7"

env:
  - DATABASE_URI="dbname='politico_test' host='127.0.0.1' port='5432' user='admin' password='admin123'"
  
# install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE politico_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres

# run pytest
script:
  - pytest --cov=app tests/v2

# then post the results to coveralls
after_success:
  - coveralls
